# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{chillfile}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["dpree"]
  s.date = %q{2010-12-07}
  s.description = %q{Let your files chill on the couch}
  s.email = %q{whiterabbit.init@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    "LICENSE",
    "README.md",
    "bin/chillfile",
    "lib/chillfile.rb",
    "lib/chillfile/cli.rb",
    "lib/chillfile/config.rb",
    "lib/chillfile/database.rb",
    "lib/chillfile/models.rb",
    "lib/models/base.rb",
    "lib/models/chilling_file.rb",
    "spec/lib/chilling_file_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/test_dir_helper.rb",
    "spec/test_dir/foo.fx"
  ]
  s.homepage = %q{http://github.com/dpree/chillfile}
  s.require_paths = [["bin", "lib"]]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Tiny tool to sync filesystem with couchdb}
  s.test_files = [
    "spec/lib/chilling_file_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/test_dir_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<couchrest>, [">= 0"])
      s.add_runtime_dependency(%q<couchrest_model>, [">= 0"])
      s.add_runtime_dependency(%q<treedisha>, [">= 0"])
      s.add_runtime_dependency(%q<json>, [">= 0"])
      s.add_runtime_dependency(%q<thor>, [">= 0"])
      s.add_runtime_dependency(%q<couchrest>, ["~> 1.0.1"])
      s.add_runtime_dependency(%q<couchrest_model>, ["~> 1.0.1"])
      s.add_development_dependency(%q<rspec>, ["~> 2.0.0"])
    else
      s.add_dependency(%q<couchrest>, [">= 0"])
      s.add_dependency(%q<couchrest_model>, [">= 0"])
      s.add_dependency(%q<treedisha>, [">= 0"])
      s.add_dependency(%q<json>, [">= 0"])
      s.add_dependency(%q<thor>, [">= 0"])
      s.add_dependency(%q<couchrest>, ["~> 1.0.1"])
      s.add_dependency(%q<couchrest_model>, ["~> 1.0.1"])
      s.add_dependency(%q<rspec>, ["~> 2.0.0"])
    end
  else
    s.add_dependency(%q<couchrest>, [">= 0"])
    s.add_dependency(%q<couchrest_model>, [">= 0"])
    s.add_dependency(%q<treedisha>, [">= 0"])
    s.add_dependency(%q<json>, [">= 0"])
    s.add_dependency(%q<thor>, [">= 0"])
    s.add_dependency(%q<couchrest>, ["~> 1.0.1"])
    s.add_dependency(%q<couchrest_model>, ["~> 1.0.1"])
    s.add_dependency(%q<rspec>, ["~> 2.0.0"])
  end
end

